var data = {
	attribute: {
		"end_user_description": "Used by the Badge-O-Matic tool to indicate objects created by the tool", 
		"read_only": 0, 
		"modified_timestamp": 1297290464, 
		"pub_title": "Badge-O-Matic", 
		"resource_name": "attribute", 
		"friendly_id": "badge-o-matic", 
		"attributes": [], 
		"created_timestamp": 1297290464, 
		"pub_description": JSON.stringify({}), 
		"end_user_title": "Badge-O-Matic", 
		"id": 19895
	},
	url: {
		"end_user_description": "You are a total Newbie.", 
		"read_only": 0, 
		"modified_timestamp": 1297290464, 
		"pub_title": "Newbie", 
		"url": "http://virtualgoods.bigdoor.com/media/image/xp/trophies/xp1.64.png", 
		"is_media_url": 1, 
		"is_for_end_user_ui": 1, 
		"created_timestamp": 1297290464, 
		"pub_description": JSON.stringify({}), 
		"end_user_title": "Newbie", 
		"attributes": [
			{
				"end_user_description": null, 
				"read_only": 1, 
				"modified_timestamp": 1265983532, 
				"pub_title": "Preview", 
				"resource_name": "attribute", 
				"friendly_id": "7a0670c7e0cb4bc280cc67276fce5754", 
				"attributes": [], 
				"created_timestamp": 1263941758, 
				"pub_description": JSON.stringify({}),
				"end_user_title": null, 
				"id": 13
			}
		], 
		"id": 30013, 
		"resource_name": "url"
	},
	currency: {
		"end_user_description": "Earn points by interacting with this site", 
		"read_only": 0, 
		"modified_timestamp": 1293730658, 
		"pub_title": "XP", 
		"currency_type_title": "Non-Redeemable Experience Points (XP)", 
		"currency_type_id": 5, 
		"exchange_rate": "130.00", 
		"resource_name": "currency", 
		"urls": [], 
		"created_timestamp": 1293730658, 
		"pub_description": JSON.stringify({instant:117}), 
		"end_user_title": "XP", 
		"relative_weight": 1, 
		"id": 8862, 
		"currency_type_description": ""
	},
	named_award: {
		"end_user_description": "for the only one", 
		"read_only": 0, 
		"modified_timestamp": 1297497767, 
		"pub_title": "test", 
		"collection_uri": "/api/publisher/d26140a611d644a99183ed908d819257/named_award_collection/2705", 
		"named_award_collection_id": 2705, 
		"resource_name": "named_award", 
		"urls": [], 
		"created_timestamp": 1297497767, 
		"pub_description": JSON.stringify({instant:117}), 
		"end_user_title": "this is only a test", 
		"relative_weight": null, 
		"id": 7293
	},
	named_award_collection: {
		"end_user_description": "it is only a test", 
		"read_only": 0, 
		"modified_timestamp": 1297497683, 
		"pub_title": "testing", 
		"named_awards": [
			{
				"end_user_description": "for the only one", 
				"read_only": 0, 
				"modified_timestamp": 1297497767, 
				"pub_title": "test", 
				"collection_uri": "/api/publisher/d26140a611d644a99183ed908d819257/named_award_collection/2705", 
				"named_award_collection_id": 2705, 
				"resource_name": "named_award", 
				"urls": [], 
				"created_timestamp": 1297497767, 
				"pub_description": JSON.stringify({}),
				"end_user_title": "this is only a test", 
				"relative_weight": null, 
				"id": 7293
			}
		], 
		"non_secure": 0, 
		"resource_name": "named_award_collection", 
		"urls": [], 
		"created_timestamp": 1297497683, 
		"pub_description": JSON.stringify({}),
		"end_user_title": "testing", 
		"id": 2705
	},
	named_level: {
		"end_user_description": "You are a total Newbie.", 
		"read_only": 0, 
		"modified_timestamp": 1293730658, 
		"pub_title": "Newbie", 
		"collection_uri": "/api/publisher/d26140a611d644a99183ed908d819257/named_level_collection/5700", 
		"created_timestamp": 1293730658, 
		"resource_name": "named_level", 
		"urls": [
			{
				"end_user_description": "You are a total Newbie.", 
				"read_only": 0, 
				"modified_timestamp": 1293730659, 
				"pub_title": "Newbie", 
				"url": "http://virtualgoods.bigdoor.com/media/image/xp/trophies/xp1.100.png", 
				"is_media_url": 1, 
				"is_for_end_user_ui": 1, 
				"created_timestamp": 1293730659, 
				"pub_description": JSON.stringify({}),
				"end_user_title": "Newbie", 
				"attributes": [
					{
						"end_user_description": null, 
						"read_only": 1, 
						"modified_timestamp": 1265983532, 
						"pub_title": "Preview", 
						"resource_name": "attribute", 
						"friendly_id": "7a0670c7e0cb4bc280cc67276fce5754", 
						"attributes": [], 
						"created_timestamp": 1263941758, 
						"pub_description": JSON.stringify({}),
						"end_user_title": null, 
						"id": 13
					}
				], 
				"id": 21505, 
				"resource_name": "url"
			}
		], 
		"attributes": [], 
		"threshold": 10, 
		"pub_description": JSON.stringify({}),
		"end_user_title": "Newbie", 
		"named_level_collection_id": 5700, 
		"id": 27236
	},
	named_level_collection: {
		"end_user_description": "Earn points by interacting with this site", 
		"read_only": 0, 
		"modified_timestamp": 1293730658, 
		"pub_title": "XP", 
		"named_levels": [
			{
				"end_user_description": "You are a total Newbie.", 
				"read_only": 0, 
				"modified_timestamp": 1293730658, 
				"pub_title": "Newbie", 
				"collection_uri": "/api/publisher/d26140a611d644a99183ed908d819257/named_level_collection/5700", 
				"created_timestamp": 1293730658, 
				"resource_name": "named_level", 
				"urls": [], 
				"attributes": [], 
				"threshold": 10, 
				"pub_description": JSON.stringify({}),
				"end_user_title": "Newbie", 
				"named_level_collection_id": 5700, 
				"id": 27236
			}, 
			{
				"end_user_description": "You are a site Pro", 
				"read_only": 0, 
				"modified_timestamp": 1293730658, 
				"pub_title": "Pro", 
				"collection_uri": "/api/publisher/d26140a611d644a99183ed908d819257/named_level_collection/5700", 
				"created_timestamp": 1293730658, 
				"resource_name": "named_level", 
				"urls": [], 
				"attributes": [], 
				"threshold": 750, 
				"pub_description": JSON.stringify({}),
				"end_user_title": "Pro", 
				"named_level_collection_id": 5700, 
				"id": 27237
			}
		], 
		"currency_id": 10373, 
		"resource_name": "named_level_collection", 
		"urls": [], 
		"attributes": [
			{
				"end_user_description": "Used by the Studio-O-Matic tool to associate a badge track with an activity", 
				"read_only": 0, 
				"modified_timestamp": 1294884693, 
				"pub_title": "Studio-O-Matic (search)", 
				"resource_name": "attribute", 
				"friendly_id": "studio-activity-search", 
				"attributes": [], 
				"created_timestamp": 1294884693, 
				"pub_description": JSON.stringify({}),
				"end_user_title": "Studio-O-Matic (search)", 
				"id": 16859
			}
		], 
		"created_timestamp": 1296685218, 
		"pub_description": JSON.stringify({}),
		"end_user_title": "Search", 
		"id": 5700
	},
	named_good: {
		"end_user_description": "fsadfsadfa", 
		"read_only": 0, 
		"modified_timestamp": 1296413898, 
		"pub_title": "fdsafasdfd", 
		"named_good_collection_id": 2011, 
		"collection_uri": "/api/publisher/d26140a611d644a99183ed908d819257/named_good_collection/2011", 
		"resource_name": "named_good", 
		"urls": [], 
		"attributes": [], 
		"created_timestamp": 1296413898, 
		"pub_description": JSON.stringify({instant:112}),
		"end_user_title": "fdsafadsf", 
		"relative_weight": 1, 
		"id": 6268
	},
	named_good_collection: {
		"end_user_description": "safsdafsadf", 
		"read_only": 0, 
		"modified_timestamp": 1296413890, 
		"pub_title": "dfsadfa", 
		"resource_name": "named_good_collection", 
		"urls": [], 
		"attributes": [], 
		"created_timestamp": 1296413890, 
		"pub_description": JSON.stringify({}),
		"end_user_title": "dfsafasdf", 
		"id": 2011, 
		"named_goods": [
			{
				"end_user_description": "fsadfsadfa", 
				"read_only": 0, 
				"modified_timestamp": 1296413898, 
				"pub_title": "fdsafasdfd", 
				"named_good_collection_id": 2011, 
				"collection_uri": "/api/publisher/d26140a611d644a99183ed908d819257/named_good_collection/2011", 
				"resource_name": "named_good", 
				"urls": [], 
				"attributes": [], 
				"created_timestamp": 1296413898, 
				"pub_description": JSON.stringify({}),
				"end_user_title": "fdsafadsf", 
				"relative_weight": 1, 
				"id": 6268
			}, 
			{
				"end_user_description": null, 
				"read_only": 0, 
				"modified_timestamp": 1296532099, 
				"pub_title": "testing ", 
				"named_good_collection_id": 2011, 
				"collection_uri": "/api/publisher/d26140a611d644a99183ed908d819257/named_good_collection/2011", 
				"resource_name": "named_good", 
				"urls": [], 
				"attributes": [], 
				"created_timestamp": 1296532099, 
				"pub_description": null, 
				"end_user_title": null, 
				"relative_weight": null, 
				"id": 6269
			}
		]
	},
	named_transaction_group: {
		"end_user_description": "Earn points by interacting with this site", 
		"read_only": 0, 
		"end_user_cap": 10, 
		"pub_title": "XP", 
		"named_transactions": [
			{
				"end_user_description": "Earn points by interacting with this site", 
				"default_amount": "1.00", 
				"modified_timestamp": 1297290466, 
				"pub_title": "XP", 
				"named_good": null, 
				"id": 615133, 
				"named_transaction_group_ratio": "-1.00", 
				"named_transaction_is_primary": 1, 
				"currency_id": 10958, 
				"is_source": 1, 
				"resource_name": "named_transaction", 
				"read_only": 0, 
				"variable_amount_allowed": 1, 
				"vendor_publisher_title": null, 
				"attributes": [
					{
						"end_user_description": "Used by the Badge-O-Matic tool to indicate objects created by the tool", 
						"read_only": 0, 
						"modified_timestamp": 1297290464, 
						"pub_title": "Badge-O-Matic", 
						"resource_name": "attribute", 
						"friendly_id": "badge-o-matic", 
						"attributes": [], 
						"created_timestamp": 1297290464, 
						"pub_description": JSON.stringify({}),
						"end_user_title": "Badge-O-Matic", 
						"id": 19895
					}, 
					{
						"end_user_description": "Used by the Badge-O-Matic tool to associate a badge track with a transaction", 
						"read_only": 0, 
						"modified_timestamp": 1297290465, 
						"pub_title": "Badge-O-Matic (7334)", 
						"resource_name": "attribute", 
						"friendly_id": "badge_o_matic_7334", 
						"attributes": [], 
						"created_timestamp": 1297290465, 
						"pub_description": JSON.stringify({}),
						"end_user_title": "Badge-O-Matic (7334)", 
						"id": 19896
					}
				], 
				"created_timestamp": 1297290466, 
				"pub_description": JSON.stringify({}),
				"end_user_title": "XP", 
				"currency": {
					"end_user_description": "Earn points by interacting with this site", 
					"read_only": 0, 
					"modified_timestamp": 1297290464, 
					"pub_title": "XP", 
					"currency_type_title": "Non-Redeemable Experience Points (XP)", 
					"currency_type_id": 5, 
					"exchange_rate": "130.00", 
					"resource_name": "currency", 
					"urls": [], 
					"created_timestamp": 1297290464, 
					"pub_description": JSON.stringify({}),
					"end_user_title": "XP", 
					"relative_weight": 1, 
					"id": 10958, 
					"currency_type_description": ""
				}, 
				"notifiable_event": 0
			}
		], 
		"modified_timestamp": 1297290466, 
		"end_user_cap_interval": 15, 
		"challenge_response_enabled": 0, 
		"non_secure": 1, 
		"urls": [], 
		"created_timestamp": 1297290466, 
		"pub_description": JSON.stringify({}),
		"end_user_title": "XP", 
		"id": 612144, 
		"resource_name": "named_transaction_group"
	},
	end_user: {
		"read_only": 0, 
		"modified_timestamp": 1294886818, 
		"resource_name": "end_user", 
		"award_summaries": [], 
		"best_guess_profile_img": null, 
		"level_summaries": [
			{
				"end_user_description": "Unlocked on first check in", 
				"named_level_collection_id": 5701, 
				"modified_timestamp": 1294886819, 
				"pub_title": "Just Arrived", 
				"collection_uri": "/api/publisher/d26140a611d644a99183ed908d819257/named_level_collection/5701", 
				"transaction_group_id": "6444089e1ebf11e0a42675f8a5e82d6c", 
				"named_level_id": 27242, 
				"leveled_up": false, 
				"created_timestamp": 1294886819, 
				"urls": [
					{
						"end_user_description": "Unlocked on first check in", 
						"read_only": 0, 
						"modified_timestamp": 1293730663, 
						"pub_title": "Just Arrived", 
						"url": "http://virtualgoods.bigdoor.com/media/image/checkin/visitor/checkin1.100.png", 
						"is_media_url": 1, 
						"is_for_end_user_ui": 1, 
						"created_timestamp": 1293730663, 
						"pub_description": JSON.stringify({}),
						"end_user_title": "Just Arrived", 
						"attributes": [
							{
								"end_user_description": null, 
								"read_only": 1, 
								"modified_timestamp": 1265983532, 
								"pub_title": "Preview", 
								"resource_name": "attribute", 
								"friendly_id": "7a0670c7e0cb4bc280cc67276fce5754", 
								"attributes": [], 
								"created_timestamp": 1263941758, 
								"pub_description": JSON.stringify({}),
								"end_user_title": null, 
								"id": 13
							}
						], 
						"id": 21511, 
						"resource_name": "url"
					}
				], 
				"threshold": 1, 
				"pub_description": JSON.stringify({}),
				"end_user_title": "Just Arrived"
			}
		], 
		"sent_good_summaries": [], 
		"best_guess_name": "08986FA2-D71B-47AF-AF43-12F5122F4181", 
		"currency_balances": [
			{
				"end_user_description": "Earn points by interacting with this site", 
				"transaction_group_id": "6444089e1ebf11e0a42675f8a5e82d6c", 
				"modified_timestamp": 1294886819, 
				"pub_title": "XP", 
				"urls": [], 
				"current_balance": "5.00", 
				"adjustment_amount": "5.00", 
				"currency_id": 8862, 
				"previous_balance": "0.00", 
				"currency_adjusted": false, 
				"created_timestamp": 1294886819, 
				"pub_description": JSON.stringify({}),
				"end_user_title": "XP"
			}, 
			{
				"end_user_description": "Earn points by checking in.", 
				"transaction_group_id": "6444089e1ebf11e0a42675f8a5e82d6c", 
				"modified_timestamp": 1294886819, 
				"pub_title": "Check In", 
				"urls": [], 
				"current_balance": "1.00", 
				"adjustment_amount": "1.00", 
				"currency_id": 8863, 
				"previous_balance": "0.00", 
				"currency_adjusted": false, 
				"created_timestamp": 1294886819, 
				"pub_description": JSON.stringify({}),
				"end_user_title": "Check In"
			}
		], 
		"created_timestamp": 1294886818, 
		"end_user_login": "08986FA2-D71B-47AF-AF43-12F5122F4181", 
		"guid": "63f415111ebf11e0b389067a358cacd5", 
		"received_good_summaries": []
	}
}

module.exports.data = data;

